version: "3.9"

networks:
  kflip-net:
    driver: overlay
    attachable: true

services:
  kflip:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - kflip-net
    ports:
      - "3000:3000"
 

